### ISSUE TITLE
MariaDB Pasword is not used correctly

### ISSUE THREAD

**Issue by cultcom** [debops-contrib/ansible-roundcube#10]
The playbook sets a user list for role "debops.mariadb" but without a password.

This lead the mariadb role to generate a random password for "roundcube" and store it under:
```
ansible/secret/mariadb/{{ansible_hostname}}/credentials/roundcube/password
```

The variable "roundcube__database_password" generates a random password which is stored here
```
secret/credentials/{{ ansible_fqdn }}/roundcube/mysql-default/roundcube/password
```

The later of the two is used for initialising the database which breaks then. So you should change the playbook to something like this:

```
--- a/docs/playbooks/roundcube.yml
+++ b/docs/playbooks/roundcube.yml
@@ -29,6 +29,7 @@
       mariadb_users:
         - database: '{{ roundcube__database_map[roundcube__database].dbname }}'
           user: '{{ roundcube__database_map[roundcube__database].dbuser }}'
+          password: '{{ roundcube__database_map[roundcube__database].dbpass }}'
           owner: '{{ roundcube__user }}'
           group: '{{ roundcube__group }}'
           home: '{{ roundcube__home }}'
```

next when initializing the database "login_host" ist set to '{{ ansible_local.mariadb.delegate_to }}' which is not "localhost" but current hostname. As the login is only allowed for roundcube@localhost this still fails.

**Comment by ganto** [comment]
Thanks for reporting this. Not nice that this is suddenly failing. A while ago I was already using this role to setup Roundcube against MySQL. Actually this was the main purpose for me to write the role. I must have broken something along the way 👎

**Comment by ganto** [comment]
@cultcom Thanks a lot for your patches. They are merged with some cleanup work and the update to `1.1.7` as requested. Could you give it a quick try? If everything works, I'll do another release and I guess this issue could then be closed.
