### ISSUE TITLE
plugin configuration ist not handled yet

### ISSUE THREAD

**Issue by cultcom** [debops-contrib/ansible-roundcube#16]
some plugins like"managesieve" need their own configuration space. Thus there should be a mechanism to store config options for enabled plugins.

Currently the only way I found is copying prepared config files by custom tasks in the playbook.

**Comment by ganto** [comment]
You can use [roundcube_local_config_map](https://debops-contrib.readthedocs.io/en/latest/ansible/roles/ansible-roundcube/docs/defaults.html#envvar-roundcube__local_config_map). This will allow you to add any configuration to the `config.php.inc`. Maybe I should add an example for this in the documentation. In my inventory I use this e.g. for:
```
# Global custom configuration
roundcube_local_config_map:
  managesieve_host: 'tls://{{ mail_relay_host }}'
```
In this example `mail_relay_host` is just a globally defined variable that I use in various places.

Can you show me how such a custom configuration file looks like in your case?

**Comment by cultcom** [comment]
I did not know that the plugin config options may be placed in the main config as well, so this issue is quite irrelevant now. Thanks for the hint.
